env: antmaze-large-diverse-v2
behavior_model_path: ./model/diffusion_trained_models/antmaze-large-diverse-v2/actor.pth
dataset_dir: ./d4rl/datasets/ant_maze_v2/Ant_maze_hardest-maze_noisy_multistart_True_multigoal_True_sparse_fixed.hdf5
pretrain_model: ./models/offline_trained_models/antmaze-large-diverse-v2
pretrain_step: 2000000
lambd: 0.3
osc_alpha: 4.0
osc_epsilon: 1.5
lambd_end: 0.35
lambd_cool: true
actor_lr: 0.0001
actor_dropout: 0.0
antmaze_no_normalize: true
discount: 0.995
eval_episodes: 100
eval_freq: 50000
work_dir: train_finetune
