env: halfcheetah-medium-expert-v2
behavior_model_path: ./model/diffusion_trained_models/halfcheetah-medium-expert-v2/actor.pth
work_dir: train_offline
dataset_dir: ./d4rl/datasets/gym_mujoco_v2/halfcheetah_medium_expert-v2.hdf5
lambd: 2.25
osc_alpha: 2.5
osc_epsilon: 0.3
max_timesteps: 2000000