env: walker2d-medium-replay-v2
behavior_model_path: ./model/diffusion_trained_models/walker2d-medium-replay-v2/actor.pth
work_dir: train_offline
dataset_dir: ./d4rl/datasets/gym_mujoco_v2/walker2d_medium_replay-v2.hdf5
lambd: 0.3
osc_alpha: 10.0
osc_epsilon: 0.5
max_timesteps: 2000000
