env: walker2d-medium-v2
behavior_model_path: ./model/diffusion_trained_models/walker2d-medium-v2/actor.pth
work_dir: train_offline
dataset_dir: ./d4rl/datasets/gym_mujoco_v2/walker2d_medium-v2.hdf5
lambd: 0.4
osc_alpha: 10.0
osc_epsilon: 0.4
max_timesteps: 3000000
